[versions]
slf4j = "2.0.12"
junit5 = "5.10.2"
# Check the newest Vaadin version at https://github.com/vaadin/platform/tags
# This is the latest stable Vaadin 14 version, or prev stable version if vaadin14_next_version is stable
vaadin14 = "14.11.10"
# Latest Vaadin 14 version, may be unstable or stable
vaadin14next = "14.11.10"
# Vaadin 22: Don't test on Vaadin 22.1.0 and higher: it requires the pro license
vaadin22 = "22.0.9"
# Vaadin 23: Don't test on Vaadin 23.5.0 and higher; it requires the pro license
vaadin23 = "23.4.1"
vaadin24 = "24.3.12"
vaadin24next = "24.4.0.beta4"

# Check newest Hilla version at https://github.com/vaadin/hilla/tags
hilla2next = "2.5.6"
hilla2 = "2.5.6"
hilla1 = "1.3.33"

[libraries]
dynatest = "com.github.mvysny.dynatest:dynatest:0.25"
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
junit-jupiterapi = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit5" }
vaadin-v14-core = { module = "com.vaadin:vaadin-core", version.ref = "vaadin14" }
vaadin-v14next-core = { module = "com.vaadin:vaadin-core", version.ref = "vaadin14next" }
vaadin-v22-core = { module = "com.vaadin:vaadin-core", version.ref = "vaadin22" }
vaadin-v23-core = { module = "com.vaadin:vaadin-core", version.ref = "vaadin23" }
vaadin-v24-core = { module = "com.vaadin:vaadin-core", version.ref = "vaadin24" }
vaadin-v24next-core = { module = "com.vaadin:vaadin-core", version.ref = "vaadin24next" }
jetbrains-annotations = "org.jetbrains:annotations:24.1.0"
javax-servletapi = "javax.servlet:javax.servlet-api:4.0.1"
jakarta-servletapi = "jakarta.servlet:jakarta.servlet-api:5.0.0"
karibu-testing-v24 = "com.github.mvysny.kaributesting:karibu-testing-v24:2.1.5"
karibu-testing-v10 = "com.github.mvysny.kaributesting:karibu-testing-v10:1.3.24"
hilla-v2 = { module = "dev.hilla:hilla", version.ref = "hilla2" }
hilla-v2next = { module = "dev.hilla:hilla", version.ref = "hilla2next" }
hilla-v1 = { module = "dev.hilla:hilla", version.ref = "hilla1" }
toml4j = "org.tomlj:tomlj:1.1.1"
